In [21]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])

In [22]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [23]:
a = np.delete(a, range(0,2) ,0)
print(a)

[[5 6 7]
 [7 8 9]]


In [ ]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

# change path if necessary
import sys
my_path = r'C:\Users\utente\Documents\GitHub\Project2'
sys.path.insert(0,my_path + r'/code/Flavio')

import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
print('TensorFlow imported')

import dictionary_helpers as dh

# imports
import numpy as np 
import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers import Dense

print('Keras imported')

# fix random seed for reproducibility
np.random.seed(666)

In [ ]:
import os
os.chdir(r'C:\Users\utente\Desktop\data\twitter_datasets_stanford')

glove_dict = dh.build_glove_dict('glove.twitter.27B.100d.txt')

print('glove_dict length = ' ,len(glove_dict))

print('Features of \',\' : \n', glove_dict[','])


In [ ]:
import os
os.chdir(r'C:\Users\utente\Desktop\data\twitter_datasets_epfl\short')
#os.chdir(r'C:\Users\utente\Desktop\data\twitter_datasets_epfl\full')

tweets = dh.build_tweets_matrix('all_short_processed.txt')
        
print('tweets lenght: ', len(tweets))

print('tweets sample (tweets[0]) :', tweets[1])

In [ ]:
import progressbar

tweetlen = len(tweets)

bar = progressbar.ProgressBar(maxval=tweetlen, widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])

feat_size = 100

sent_size = 10

delete_win = 1000

In [ ]:
X = np.empty([len(tweets), feat_size*sent_size])

bar.start()

k = 0

i = 0

while i < tweetlen:
    
    if (i%delete_win == 0 & i!=0):
        tweets = np.delete(tweets, arange(0,delete_win) ,0)
        k = k+1
        gc.collect()
    
    feats = []
    for j in range(len(tweets[i-k*delete_win])):
        if tweets[i-k*delete_win][j] in glove_dict:
            feats.append(glove_dict[tweets[i-k*delete_win][j]])
        else:
            feats.append([0]*feat_size)

    X[i]= np.hstack((np.mean(feats, axis=0), np.amax(feats, axis=0), np.amin(feats, axis=0)))
        
    i = i+1
    
    bar.update(i)
    
bar.finish()
    
print('X shape: ' , X.shape)
print('X[9][5] = ', X[9][5], ' ', type(X[9][5]))
print('X[9] = ', X[9])


labels = []

#halfway = 1127644 #For the full dataset
halfway = 90233    #For the short dataset

#For the full dataset---

for i in range(halfway):
    labels.append(1)
for i in range(len(tweets)-halfway):
    labels.append(0)

Y = np.asarray(labels)